### PR TITLE
Add Subscribe Button

### PR DESCRIPTION
**Pull request by pradeepgangwar**
Link of your fork to view changes: http://pradeepgangwar.tech/nybles.github.io/

Briefly describe what changes you made:
*  Added Subscribe option that saves the email of person subscribing to nybles.

### CODE REVIEW

**Comment by himanshub16** [comment]
Sorry for the delay. The internship takes all my time.
Here are my recommendations as I saw the site on your fork.
* Subscribe button should not be translucent/transparent. Material UI has buttons like cards.
* The text "subscribe to nybles" in a modal window should have some darker colour or heavier font as it improves readability.

**Comment by pradeepgangwar** [comment]
@himanshub16  I will try to add these things.

**Comment by gauthamzz** [comment]
@pradeepgangwar whats the progress ,on changes said by @himanshub16

**Comment by pradeepgangwar** [comment]
@gauthamzz i have made requested changes to my best. Please review them.

**Pull request merged**
