### PR TITLE
added github corner

### PR DESCRIPTION
**Pull request by aswinzz**
Link of your fork to view changes: *http://aswinzz.tech/nybles.github.io*

### CODE REVIEW

**Comment by mubaris** [comment]
It would be better if the color matches the theme color.

**Comment by aswinzz** [comment]
screenshot from 2017-04-03 14-28-34
is this okay?

**Comment by mubaris** [comment]
Use color #e95420

**Comment by aswinzz** [comment]
Done

**Comment by aswinzz** [comment]
screenshot from 2017-04-03 14-34-36

**Comment by mubaris** [comment]
I already changed your code :laughing:

**Comment by aswinzz** [comment]
:+1: )

**Comment by gauthamzz** [comment]
why when we already have a github button and a github in menu :/ we should remove @mubaris

**Comment by mubaris** [comment]
Github button is not cool

**Comment by gauthamzz** [comment]
then lets remove it

**Comment by mubaris** [comment]
What about facebook button?

**Pull request merged**
