### PR TITLE
This one looks good for a sample pic.

### PR DESCRIPTION
**Pull request by surasnayak**
**Remove above lines, after reading them**

Link of your fork to view changes: *Enter github.io link here*

Any [issue](https://github.com/nybles/nybles.github.io/issues) your want to refer to?
*# issue number *

Briefly describe what changes you made:
* Added a new sample image of hackathon.
* 
*

### CODE REVIEW

**Comment by gauthamzz** [comment]
can i see a live link ?
please enable gh pages 
btw why did you set theme ?

**Comment by surasnayak** [comment]
Here is the link.
Please do have a look.
https://surasnayak.github.io/nybles.github.io/

**Comment by gauthamzz** [comment]
please change the sample image from hack in the north to something related to nybles

**Comment by gauthamzz** [comment]
closing due to inactivity

**Pull request closed without merging**
