### PR TITLE
Created markdown editor to write blog online

### PR DESCRIPTION
**Pull request by himanshub16**
Fix to #28 
* More features and fixes can be added in future.
* The submission can be handled by this script : https://github.com/himanshub16/nybles.github.io/blob/master/markdown-editor/cgi-bin/nybles-submit.py
* The script mentioned above can be modified appropriately and placed on Geekhaven's server, and serve as our handler.

### CODE REVIEW

**Comment by himanshub16** [comment]
The markdown editor is forked from http://jbt.github.io/markdown-editor/ .

**Comment by gauthamzz** [comment]
Can u show me gh

**Comment by himanshub16** [comment]
What?
https://himanshub16.github.io/nybles.github.io/markdown-editor/

**Comment by gauthamzz** [comment]
we need something to redirect back to home.
I was thinking we make this another project under nybles organisation and link them together ?

**Pull request closed without merging**
