### PR TITLE
Enabled Global Search

### PR DESCRIPTION
**Pull request by pradeepgangwar**

### CODE REVIEW

**Comment by himanshub16** [comment]
Please make sure that the elements follow the same design (Material in this case). For now, I've fixed this. [check commit](https://github.com/nybles/nybles.github.io/commit/1a078220bab01b563fd59a428de5b1312008402d#diff-822e9cf54ee310f9a7ebd0d16c9ae066).

**Comment by himanshub16** [comment]
@mubaris Please don't merge PRs without scrutinising.

**Comment by gauthamzz** [comment]
@mubaris dont merge man ,this has so many faults :/

**Comment by gauthamzz** [comment]
screenshot from 2017-03-19 14-03-20
box is not comming and Search for... is not conventional

**Pull request merged**
